"""Generate Rust lookup tables for non-decimal Unicode numeric characters."""

from __future__ import annotations

import unicodedata
from collections import defaultdict
from pathlib import Path

from natsort.unicode_numbers import digits_no_decimals, numeric_no_decimals


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "rust-port" / "src" / "unicode_numeric.rs"


def rust_character(character: str) -> str:
    """Return a Unicode character as a Rust char literal."""
    return f"'\\u{{{ord(character):X}}}'"


def rust_float(value: float) -> str:
    """Return a Python float in Rust-compatible syntax."""
    rendered = repr(value)

    if rendered == "inf":
        return "f64::INFINITY"

    if rendered == "-inf":
        return "f64::NEG_INFINITY"

    if rendered == "nan":
        return "f64::NAN"

    return rendered


def group_digit_characters() -> dict[int, list[str]]:
    """Group non-decimal Unicode digits by integer value."""
    grouped: dict[int, list[str]] = defaultdict(list)

    for character in digits_no_decimals:
        value = unicodedata.digit(character)
        grouped[value].append(character)

    return dict(sorted(grouped.items()))


def group_numeric_characters() -> dict[float, list[str]]:
    """Group non-decimal Unicode numerics by floating-point value."""
    grouped: dict[float, list[str]] = defaultdict(list)

    for character in numeric_no_decimals:
        value = unicodedata.numeric(character)
        grouped[value].append(character)

    return dict(sorted(grouped.items()))


def write_match_arm(
    output: list[str],
    characters: list[str],
    value: str,
) -> None:
    """Write one grouped Rust match arm."""
    literals = [rust_character(character) for character in characters]

    line = "        "

    for index, literal in enumerate(literals):
        addition = literal if index == 0 else f" | {literal}"

        if len(line) + len(addition) > 96:
            output.append(line)
            line = "        " + addition.lstrip()
        else:
            line += addition

    line += f" => Some({value}),"
    output.append(line)


def generate() -> str:
    """Generate the complete Rust source file."""
    digit_groups = group_digit_characters()
    numeric_groups = group_numeric_characters()

    output = [
        "// This file is automatically generated.",
        "// Do not edit it manually.",
        "//",
        "// Source:",
        "// natsort/unicode_numbers.py",
        "// natsort/unicode_numeric_hex.py",
        "",
        "/// Return the integer value of a non-decimal Unicode digit.",
        "pub(crate) fn unicode_digit_value(character: char) -> Option<u8> {",
        "    match character {",
    ]

    for value, characters in digit_groups.items():
        write_match_arm(output, characters, str(value))

    output.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
            "/// Return the floating-point value of a non-decimal Unicode numeric character.",
            "pub(crate) fn unicode_numeric_value(character: char) -> Option<f64> {",
            "    match character {",
        ]
    )

    for value, characters in numeric_groups.items():
        write_match_arm(output, characters, rust_float(value))

    output.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "",
            "    #[test]",
            "    fn returns_values_for_unicode_digits() {",
            "        assert_eq!(unicode_digit_value('①'), Some(1));",
            "        assert_eq!(unicode_digit_value('②'), Some(2));",
            "        assert_eq!(unicode_digit_value('⁹'), Some(9));",
            "    }",
            "",
            "    #[test]",
            "    fn returns_values_for_broader_unicode_numerics() {",
            "        assert_eq!(unicode_numeric_value('①'), Some(1.0));",
            "        assert_eq!(unicode_numeric_value('Ⅱ'), Some(2.0));",
            "        assert_eq!(unicode_numeric_value('⅓'), Some(1.0 / 3.0));",
            "    }",
            "",
            "    #[test]",
            "    fn rejects_non_numeric_characters() {",
            "        assert_eq!(unicode_digit_value('A'), None);",
            "        assert_eq!(unicode_numeric_value('A'), None);",
            "    }",
            "}",
            "",
        ]
    )

    return "\n".join(output)


def main() -> None:
    """Generate and write the Rust lookup module."""
    generated_source = generate()

    OUTPUT_FILE.write_text(generated_source, encoding="utf-8")

    print(f"Generated: {OUTPUT_FILE}")
    print(f"Non-decimal digit characters: {len(digits_no_decimals)}")
    print(f"Non-decimal numeric characters: {len(numeric_no_decimals)}")


if __name__ == "__main__":
    main()